### ISSUE TITLE
Produce Junit XML format instead of .Junit

### ISSUE THREAD

**Issue by ssharma0312** [XCTestHTMLReport/XCTestHTMLReport#215]
Hi There

First of all, thank you for creating this library.

The `-j` produces the junit report but in `.junit` format which is not compatible with Gitlab pipelines. Is there a way to produce Junit XML style report?

**Comment by nacho4d** [comment]
Are you using the latest latest source?

I am using `xchtmlreport` build from latest develop and it works with my gitlab pipeline.

Here is a part of my .gitlab-ci.yml

```yml
test-ios-ProjectName:
  stage: test
  script:
    - xcrun xcodebuild -version
    - XCODE_TEST_RESULTS=${CI_PROJECT_DIR}/xcodeTestResults.xcresult
    - xcrun xcodebuild -project ProjectName.xcodeproj/ -scheme SchemeName -destination "platform=iOS Simulator,name=iPhone 8,OS=latest" clean test -resultBundlePath $XCODE_TEST_RESULTS -enableCodeCoverage YES -quiet
  after_script:
    # Generate HTML test report (index.html) and JUNIt report (report.junit)
    - XCODE_TEST_RESULTS=${CI_PROJECT_DIR}/xcodeTestResults.xcresult
    - xchtmlreport -r $XCODE_TEST_RESULTS -j -i
    - mv ${XCODE_TEST_RESULTS}/report.junit ${CI_PROJECT_DIR}/report.junit
    - mv ${CI_PROJECT_DIR}/index.html ${CI_PROJECT_DIR}/index.html
    - cd ${CI_PROJECT_DIR}
    # Also generate a Zip file from the original xcresult bundle
    - zip -r -q -X xcodeTestResults.zip $(basename "$XCODE_TEST_RESULTS1") || true
  tags:
    - ios-xcode12
  only:
    refs:
      - merge_requests
  artifacts:
    paths:
      - index.html
      - xcodeTestResults.zip
    reports:
      junit: report.junit
```
